apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: jumptotech123
  MYSQL_DATABASE: restaurant
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
